covacuate/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('hill_climb.urls')),
]

hill_climb/urls.py
from django.urls import path
from .views import homepage, show_map, get_city, about, get_safest_city

app_name = 'hill_climb'

urlpatterns = [
    path('', homepage, name='home'),
    path('evacuate/', show_map, name='map'),
    path('evacuate/<province>', get_city, name='get_city'),
    path('get_safest_city/', get_safest_city, name='get_safest_city'),
    path('about/', about, name='about'),
]

hill_climb/models.py
from django.db import models

# Create your models here.

hill_climb/views.py
from hill_climb import HillClimb, coVacuate
from hill_climb.HillClimb import HillClimb
from django.http.response import JsonResponse
from django.shortcuts import render
from django.http import HttpResponse


# Create your views here.
def homepage(request):
    return render(request, 'homepage.html', {})

def show_map(request):
    return render(request, 'evacuate.html', {})

def get_city(request, province):
    city_list = coVacuate.get_city_of_province(province)
    return JsonResponse({
        'province':province,
        'cities':city_list
        })

def about(request):
    return render(request, 'about.html', {})

def get_safest_city(request):
    province_name = request.GET.get('province_name')
    print("INI"+province_name)
    city_name = request.GET.get('city_name')
    print("INI"+city_name)
    # city_name = request.POST['city_name']
    hc = HillClimb()
    result = hc.get_safest_city(province_name,city_name)
    response_data = {}
    index = 0
    list_result = result[0]
    origin_data = result[1].get_covid_data()
    to_json_origin = {}
    to_json_origin['city'] = result[1].get_name()
    to_json_origin['prov'] = result[2].get_name()
    to_json_origin['konfirmasi'] = origin_data['Terkonfirmasi']
    to_json_origin['sembuh'] = origin_data['Sembuh']
    to_json_origin['meninggal'] = origin_data['Meninggal']
    response_data['origin'] = to_json_origin

    if len(list_result) <= 5:
        max_len_list_result = len(list_result)
    else:
        max_len_list_result = 5

    for i in range(max_len_list_result):
        el = list_result[i]
        el_to_json = {}

        city = el[1]
        data_covid_city = city.get_covid_data()
        el_to_json['city'] = city.get_name()
        el_to_json['prov'] = el[2].get_name()
        el_to_json['dist'] = city.get_dist_from_origin()
        el_to_json['konfirmasi'] = data_covid_city['Terkonfirmasi']
        el_to_json['sembuh'] = data_covid_city['Sembuh']
        el_to_json['meninggal'] = data_covid_city['Meninggal']

        response_data[index] = el_to_json
        index += 1
    response_data['count'] = index
    print("udahkeluar")
    print(response_data)
    return JsonResponse(response_data)

hill_climb/templates/about.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>About - Covacuate</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'hill_climb/about.css' %}">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@200;300;400;600&display=swap" rel="stylesheet">
</head>
<body style="font-family: 'Poppins', sans-serif; background-color: #eed75a; font-weight: 400;">
    {% include 'navbar.html' %}
    <div class="container">
        <div class="row">
            <h1 style="font-weight: 200; font-size: 500%;"><b style="font-weight: 600;">About</b> Us</h1>
            <p style="font-weight: 300;">
                This website is a product of Artificial Intelligence class project.
                The AI algorithm used is Hill Climb, with COVID data provided from each official province website in Indonesia. 
                Our team of developers:
            </p>
        </div>
        <div class="row">

            <div class="col-8">
                <div class="row">
                    <div class="card">
                        <div class="card-body">
                          <h5 class="card-title">Aji Inisti Udma Wijaya</h5>
                          <h6 class="card-subtitle mb-2">1806141126</h6>
                        </div>
                    </div>
                    <div class="card">
                        <div class="card-body">
                          <h5 class="card-title">Luqman Maulana Rizki</h5>
                          <h6 class="card-subtitle mb-2">1806205092</h6>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="card">
                        <div class="card-body">
                          <h5 class="card-title">Ronaldi Tjaidianto</h5>
                          <h6 class="card-subtitle mb-2">1806141441</h6>
                        </div>
                    </div>
                    <div class="card">
                        <div class="card-body">
                          <h5 class="card-title">Salman Ahmad Nurhoiriza</h5>
                          <h6 class="card-subtitle mb-2">1806204890</h6>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-4">
                <img src="https://i.ibb.co/XzjV0m4/Allura-Working-Remotely-2.png" alt="" width="100%">
            </div>
        </div>
    </div>
</div>
</body>
</html>

hill_climb/templates/evacuate.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Evacuate - CoVacuate</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'hill_climb/mapstyle.css' %}">
    <link rel="stylesheet" href="{% static 'hill_climb/result_modal.css' %}">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Poppins&display=swap" rel="stylesheet">
</head>
<body style="font-family: 'Poppins', sans-serif; background-color: #eed75a; font-weight: 400;">
    {% include 'navbar.html' %}
    {% include 'map.html' %}

    <div class="container">
        <div class="d-flex flex-column justify-item-center">
            <div class="p-2">
                <span>Select <b style="font-weight: 600;">Co</b>Vacuate starting point from the map or form below.</span>
            </div>
            <div class="container-fluid" style="margin-top:60vh">
                <span>Chosen <b style="font-weight: 600;">province</b>: </span>
                <select class="form-control custom-select" id="province_form">
                    <option value="Aceh">Aceh</option>
                    <option value="Bali">Bali</option>
                    <option value="Bangka Belitung">Bangka Belitung</option>
                    <option value="Bengkulu">Bengkulu</option>
                    <option value="Banten">Banten</option>
                    <option value="DKI Jakarta">DKI Jakarta</option>
                    <option value="Gorontalo">Gorontalo</option>
                    <option value="Jambi">Jambi</option>
                    <option value="Jawa Barat">Jawa Barat</option>
                    <option value="Jawa Timur">Jawa Timur</option>
                    <option value="Jawa Tengah">Jawa Tengah</option>
                    <option value="Kalimantan Utara">Kalimantan Utara</option>
                    <option value="Kalimantan Barat">Kalimantan Barat</option>
                    <option value="Kalimantan Timur">Kalimantan Timur</option>
                    <option value="Kalimantan Tengah">Kalimantan Tengah</option>
                    <option value="Kalimantan Selatan">Kalimantan Selatan</option>
                    <option value="Kepulauan Riau">Kepulauan Riau</option>
                    <option value="Lampung">Lampung</option>
                    <option value="Maluku">Maluku</option>
                    <option value="Maluku Utara">Maluku Utara</option>
                    <option value="Nusa Tenggara Barat">Nusa Tenggara Barat</option>
                    <option value="Nusa Tenggara Timur">Nusa Tenggara Timur</option>
                    <option value="Papua">Papua</option>
                    <option value="Papua Barat">Papua Barat</option>
                    <option value="Riau">Riau</option>
                    <option value="Sulawesi Utara">Sulawesi Utara</option>
                    <option value="Sulawesi Barat">Sulawesi Barat</option>
                    <option value="Sulawesi Tengah">Sulawesi Tengah</option>
                    <option value="Sulawesi Tenggara">Sulawesi Tenggara</option>
                    <option value="Sulawesi Selatan">Sulawesi Selatan</option>
                    <option value="Sumatera Utara">Sumatera Utara</option>
                    <option value="Sumatera Barat">Sumatera Barat</option>
                    <option value="Sumatera Selatan">Sumatera Selatan</option>
                    <option value="DI Yogyakarta">DI Yogyakarta</option>
                </select>
                <span id="province"></span>
                <form action="" style="margin-top: 3pt;">
                    <div class="form-group">
                        <span>Chosen <b style="font-weight: 600;">city</b>: </span>
                        <select class="form-control custom-select" id="cities">
                        </select>
                        <hr>
                        <button type="button" class="btn btn-outline-dark" onclick="getValue('province_form','cities')" data-bs-toggle="modal" data-bs-target="#resultBackdrop">Find!</button>
                        {% include 'resultModal.html' %}
                    </div>
                </form>        
            </div>        
        </div>
    </div>

    <script
        src="https://code.jquery.com/jquery-3.4.1.js"
        integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU="
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
    <script src="{% static 'hill_climb/index.js' %}"></script>  
</body>
</html>

hill_climb/templates/homepage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CoVacuate</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@200;300;400;600&display=swap" rel="stylesheet">
</head>
<body style="font-family: 'Poppins', sans-serif; background-color: #eed75a; font-weight: 400;">
    {% include 'navbar.html' %}
    <div class="container">
        <div class="row">
            <div class="col d-flex align-items-center">
                <div>
                    <h1 style="font-weight: 200; font-size: 500%;"><b style="font-weight: 600;">Co</b>Vacuate</h1>
                    <p style="font-weight: 300;">Finding you the closest, lowest number of active COVID-19 cases from anywhere you are in Indonesia.</p>
                    <a href="{% url 'hill_climb:map' %}">
                    <button type="button" class="btn btn-outline-dark">
                        Start evacuating!
                    </button>
                    </a>
                </div>
            </div>
            <div class="col">
              <img src="https://blush.design/api/download?shareUri=Ypjn1Re-m&w=800&h=800&fm=png" alt="" style="width: 100%;">
            </div>
        </div>
    </div>
</body>
</html>

hill_climb/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light" style="margin-bottom: 1%; background-color: #eed75a;">
    <a class="navbar-brand" href="{% url 'hill_climb:home' %}">
      <span style="font-weight: 200;">
          <b style="font-weight: 600;">Co</b>Vacuate
      </span>
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <a class="nav-link" href="{% url 'hill_climb:home' %}">Home</a>
        <a class="nav-link" href="{% url 'hill_climb:map' %}">Evacuate</a>
        <a class="nav-link" href="{% url 'hill_climb:about' %}">About</a>
      </div>
    </div>
</nav>

hill_climb/templates/resultModal.html
<div class="modal fade" id="resultBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="resultBackdropLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="resultBackdropLabel">Result</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body"> 
                <div class="row">
                    <div class="col">
                        <span>Safest city:</span> <br>
                        <span style="font-size: larger;"><b id="safestCity"></b></span>
                        <span style="font-size: small;" id="safestProv"></span> <br>
                        <span style="color: darkgoldenrod;" id="sameCity"></span>
                    </div>
                </div>
                <hr>
                <div class="accordion accordion-flush" id="resultAccordion">
                    <div class="accordion-item">
                      <h2 class="accordion-header" id="flush-headingTwo">
                        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseTwo" aria-expanded="false" aria-controls="flush-collapseTwo">
                          Details
                        </button>
                      </h2>
                      <div id="flush-collapseTwo" class="accordion-collapse collapse" aria-labelledby="flush-headingTwo" data-bs-parent="#resultAccordion">
                        <div class="accordion-body">
                            <table class="table table-striped table-bordered">
                                <caption>*Distance from origin city</caption>
                                <thead>
                                  <tr>
                                    <th scope="col" rowspan="2">#</th>
                                    <th scope="col" rowspan="2">City</th>
                                    <th scope="col" rowspan="2">Province</th>
                                    <th scope="col" colspan="3">COVID Data</th>
                                    <th scope="col" rowspan="2">Distance* (m)</th>
                                  </tr>
                                  <tr>
                                    <th scope="col">Confirmed</th>
                                    <th scope="col">Recovered</th>
                                    <th scope="col">Death</th>
                                  </tr>
                                </thead>
                                <tbody>
                                  <tr>
                                    <th scope="row">Origin</th>
                                    <td id="originCiti"></td>
                                    <td id="originProvince"></td>
                                    <td id="originConfirmed"></td>
                                    <td id="originRecovered"></td>
                                    <td id="originDeaths"></td>
                                    <td></td>
                                  </tr>
                                  <tr>
                                    <th scope="row">Safest</th>
                                    <td id="rsltCity"></td>
                                    <td id="rsltProvince"></td>
                                    <td id="rsltConfirmed"></td>
                                    <td id="rsltRecovered"></td>
                                    <td id="rsltDeath"></td>
                                    <td id="rsltDistance"></td>
                                  </tr>
                                </tbody>
                              </table>
                            </div>
                      </div>
                    </div>
                    <div class="accordion-item">
                      <h2 class="accordion-header" id="flush-headingThree">
                        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseThree" aria-expanded="false" aria-controls="flush-collapseThree">
                          Potential Cities
                        </button>
                      </h2>
                      <div id="flush-collapseThree" class="accordion-collapse collapse" aria-labelledby="flush-headingThree" data-bs-parent="#resultAccordion">
                        <div class="accordion-body">
                            <table class="table table-striped table-bordered">
                                <caption>*Distance from origin city</caption>
                                <caption id="noOtherPotential"></caption>
                                <thead>
                                  <tr>
                                    <th scope="col" rowspan="2">#</th>
                                    <th scope="col" rowspan="2">City</th>
                                    <th scope="col" rowspan="2">Province</th>
                                    <th scope="col" colspan="3">COVID Data</th>
                                    <th scope="col" rowspan="2">Distance* (m)</th>
                                  </tr>
                                  <tr>
                                    <th scope="col">Confirmed</th>
                                    <th scope="col">Recovered</th>
                                    <th scope="col">Death</th>
                                  </tr>
                                </thead>
                                <tbody id="potentialCities">
                                </tbody>
                              </table>
                        </div>
                      </div>
                    </div>
                  </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>